global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Ad.TradeIn.Entities.Data;
global using Ad.TradeIn.AppDomain.Users;
global using Ad.TradeIn.Infrastructure.Data.Repositories;
global using Ad.TradeIn.Infrastructure.Extensions;
global using Ad.TradeIn.AppDomain.Users.Auth;
global using Ad.TradeIn.AppCore.Users.Auth;
global using MediatR;